### ISSUE TITLE
Not being able to open Notion pages.

### ISSUE THREAD

**Issue by yaripey** [frencojobs/vscode-notion#4] opened 2021-01-11 15:23 UTC
Hi there. I can't open anything from Notion with this extension. For example, [this page](https://www.notion.so/yaripey/Test-page-for-VSCode-notion-extension-320213fb70ba48169059a17fa9dc195c). I can open it in browser, but the VSCode just shows `VSCode Notion: Loading...` in the bottom right corner for 2-3 seconds and dissapears. Nothing else happens. Maybe I need to provide some additional info?

**Comment by frencojobs** [comment] 2021-01-11 16:43
Hmmm, that page loads and works perfectly well for me though. 

![proof](https://user-images.githubusercontent.com/17830687/104211171-250bf180-5462-11eb-88e5-e520701c4503.png)

It might not be related to the webview if the tab doesn't open at all. If so can you check and share the error log in the console if any exists? You can open the console from `Help > Toggle Developer Tools`.

**Comment by alawler4** [comment] 2021-01-11 16:52
I'm having a similar problem. The test page opens just fine, but a non-test page doesn't do anything.

**Comment by yaripey** [comment] 2021-01-11 16:53
It gives me this:

![image](https://user-images.githubusercontent.com/11278566/104212860-570b5c80-543e-11eb-9303-59c0190391a9.png)

**Comment by StwGabriel** [comment] 2021-01-12 00:18
I'm having the same problem!

**Comment by StwGabriel** [comment] 2021-01-12 00:20
![image](https://user-images.githubusercontent.com/61845917/104253239-d2770900-5452-11eb-8c0b-2b46e6e19778.png)

**Comment by frencojobs** [comment] 2021-01-12 02:35
Does the error persist? I mean 
- Is the error happening to only certain pages?
- Do you still have that error after trying multiple times?
- Is the error happening to all pages and the extension is not usable at all?

And can you guys open this URL https://notion-api.frenco.dev/v1/page/320213fb70ba48169059a17fa9dc195c? To check if it's caused by the server in your VPN area or not.

**Comment by yaripey** [comment] 2021-01-12 02:41
1. No, error is happening to all pages. I tried like 10 of different ones, same result.
2. Yes, the error is the same after a lot of tries.
3. Yes, it basically adds two commands to comand pallette, you give it a link, it shows a message of loading and then never does anything else.

And yes, the link is openable in any browser. It returns a JSON with info about the page.

**Comment by frencojobs** [comment] 2021-01-12 03:03
It is definitely a weird bug, it's not reproducible on my machine, and according to the log, the error comes from this line
```ts
if (Object.keys(res.data).length < 1) {
  throw new Error("Couldn't load the data from API.")
}
```
which is only the case when the data return from API looks like this,
```json
{}
```

If viewing the API in the browser doesn't look like that, it's super weird. Then, the only case possible would be that `res.data` is `null`. I have no idea why it would be though.

May I know your VSCode version, and basic information about your machine model so that I can go through VSCode issues and check for one similar to the case? You can get the version from `code -v`.

**Comment by yaripey** [comment] 2021-01-12 03:07
Results from `code -v`: 

```
1.52.1
ea3859d4ba2f3e577a159bc91e3074c5d85c0523
x64
```

Here is my VSCode __about__ text.

![image](https://user-images.githubusercontent.com/11278566/104264131-b6e02280-5493-11eb-9c0c-f58b4ccd41bd.png)

My machine is Huawei MateBook D14, AMD Ryzen 5 3500U.

Though, there are other people who has the same bug, I doubt there is something to do with the machine.

**Comment by frencojobs** [comment] 2021-01-12 04:37
Omg I think I know what the error is. I parse the notion URL to get the ID using a regex something like this,
```ts
const pattern = /(?:https?:\/\/)?(?:www\.)?notion\.so\/([\w\.-]*)*\/?/
```
so it only matches public links without a username, so you have to use it as
```bash
# like this
https://www.notion.so/Test-page-for-VSCode-notion-extension-320213fb70ba48169059a17fa9dc195c
# not like this
https://www.notion.so/yaripey/Test-page-for-VSCode-notion-extension-320213fb70ba48169059a17fa9dc195c
```
You can get the absolute URL from the `Share > Copy Link` in Notion.

**Comment by frencojobs** [comment] 2021-01-12 05:12
v1.0.1 will contain a fix for this, by parsing URLs containing usernames. Feel free to reopen the issue if you think it's not the culprit after trying in v1.0.1.

**Closed** 2021-01-12 05:13 UTC
Labels: bug

**Comment by yaripey** [comment] 2021-01-12 05:23
Yes! Without username it works fine. The only note I would like to make is that `Share > Copy Link` still adds username to the path, at least for me. So the only way to obtain a working _absolute_ link is to remove the username from the path manually. Good to hear that it will be fixed in v1.0.1, waiting for it. Thanks.

**Comment by harshraj1311** [comment] 2022-08-05 05:27
GETTING ERROR AGAIN!
error is = "Couldn't load the data from API. "

**Comment by JQuezada0** [comment] 2022-10-14 16:53
Same

**Comment by nomm-dot** [comment] 2023-02-26 00:01
Currently getting the same issue, but when copying the link in notion there is no user or file path to change. I copy and paste to VScode and I get the "Couldn't load the date from API" or "Request failed with status code 404" errors in the bottom right corner. I am not running a VPN. I tried to publish the page and add it to a workgroup neither resolved the issue.
